apiVersion: v1
kind: Service
metadata:
  name: devops-service-nodeport
  namespace: {{ .Values.nameSpace }}
spec:
  type: NodePort
  selector:
    app: devops-project
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 80
status:
  loadBalancer: {}
